// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3FPDkJv4N0Jcg9w9mlKcPci0D8dV-7_c',
    appId: '1:682045763433:web:c689c336000f85d7a097f8',
    messagingSenderId: '682045763433',
    projectId: 'flutter-test-603b7',
    authDomain: 'flutter-test-603b7.firebaseapp.com',
    storageBucket: 'flutter-test-603b7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq_av_4niqi025ZjI7PNbnDyod7mT1XmA',
    appId: '1:682045763433:android:1793ff26a7544d4ea097f8',
    messagingSenderId: '682045763433',
    projectId: 'flutter-test-603b7',
    storageBucket: 'flutter-test-603b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvTFoW1qkTy1yzvAqzMdtNAXOU6QrA2PU',
    appId: '1:682045763433:ios:c67126b2570ebe4ca097f8',
    messagingSenderId: '682045763433',
    projectId: 'flutter-test-603b7',
    storageBucket: 'flutter-test-603b7.appspot.com',
    iosBundleId: 'com.sylo.firebasecrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvTFoW1qkTy1yzvAqzMdtNAXOU6QrA2PU',
    appId: '1:682045763433:ios:3cd6294c753428f9a097f8',
    messagingSenderId: '682045763433',
    projectId: 'flutter-test-603b7',
    storageBucket: 'flutter-test-603b7.appspot.com',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3FPDkJv4N0Jcg9w9mlKcPci0D8dV-7_c',
    appId: '1:682045763433:web:72266c5b67133e29a097f8',
    messagingSenderId: '682045763433',
    projectId: 'flutter-test-603b7',
    authDomain: 'flutter-test-603b7.firebaseapp.com',
    storageBucket: 'flutter-test-603b7.appspot.com',
  );
}
